### ISSUE TITLE
Compiled Binary for Windows

### ISSUE THREAD

**Issue by ChrisNbg** [pierrecoll/autoprox#1]
Hello,

is it possible to add an precompiled version of autoprox to this repository? It's nice to share the sources but if I'm not able to compile them this doesn't help very much ;-).

I tried to find an other page where are binarys are shared but found only a blog-post at https://blogs.technet.microsoft.com/emeaie/2013/11/04/optimizing-performance-with-automatic-proxyconfiguration-scripts-pac/ where only an older version was added (V 2.1.0.0)

Thank you for your work 👍 .

With regards
Christian

**Comment by pierrecoll** [comment]
Hello Christian,

You can find the latest version on http://ieee.azurewebsites.net/pierrelc.

I am not adding a precompiled version on GitHub  for supportability reasons.

I am planning to add some kind of EULA like the one from Sysinternals but this needs to be validated by legal.


IE AND EDGE INTERNALS SOFTWARE LICENSE TERMS

These license terms are an agreement between IE and Edge Internals (a group of Microsoft support engineers building troubleshooting tools on their own)  and you.

Please read them.

They apply to the software you are downloading from ieee.azurewebsites.net/ieeeinternals, which includes the media on which you received it, if any.The terms also apply to any IE and EDGE Internals

                · updates,

                · supplements,

                · Internet - based services, and

                · support services

for this software, unless other terms accompany those items.If so, those terms apply.



BY USING THE SOFTWARE, YOU ACCEPT THESE TERMS.

IF YOU DO NOT ACCEPT THEM, DO NOT USE THE SOFTWARE.

If you comply with these license terms, you have the rights below.

1. INSTALLATION AND USE RIGHTS. You may install and use any number of copies of the software on your devices.

2. Scope of License.The software is licensed, not sold.This agreement only gives you some rights to use the software.IE and EDGE Internals reserves all other rights.

Unless applicable law gives you more rights despite this limitation, you may use the software only as expressly permitted in this agreement.

In doing so, you must comply with any technical limitations in the software that only allow you to use it in certain ways.You may not

                ·work around any technical limitations in the binary versions of the software;

                ·reverse engineer, decompile or disassemble the binary versions of the software, except and only to the extent that applicable law expressly permits, despite this limitation;

                ·make more copies of the software than specified in this agreement or allowed by applicable law, despite this limitation;

                ·publish the software for others to copy;

                ·rent, lease or lend the software;

                ·transfer the software or this agreement to any third party; or

                ·use the software for commercial software hosting services.

3. DOCUMENTATION.Any person that has valid access to your computer or internal network may copy and use the documentation for your internal, reference purposes.

4. Export Restrictions.The software is subject to United States export laws and regulations.

                You must comply with all domestic and international export laws and regulations that apply to the software.These laws include restrictions on destinations, end users and end use.For additional information, see www.microsoft.com<http://www.microsoft.com/> / exporting <http://www.microsoft.com/exporting>.

[https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE2moGq?ver=eeb3&q=90&m=8&h=140&w=250&b=%23FFFFFFFF&l=f&x=0&y=191&s=2120&d=795&aim=true]<http://www.microsoft.com/>

Microsoft - Official Home Page<http://www.microsoft.com/>
www.microsoft.com
At Microsoft our mission and values are to help people and businesses throughout the world realize their full potential.



5. SUPPORT SERVICES.Because this software is "as is," we may not provide support services for it.

6. Entire Agreement.This agreement, and the terms for supplements, updates, Internet - based services and support services that you use, are the entire agreement for the software and support services.

7. Applicable Law.

                a.United States.If you acquired the software in the United States, Washington state law governs the interpretation of this agreement and applies to claims for breach of it, regardless of conflict of laws principles.

                The laws of the state where you live govern all other claims, including claims under state consumer protection laws, unfair competition laws, and in tort.

                b.Outside the United States.If you acquired the software in any other country, the laws of that country apply.

8. Legal Effect.This agreement describes certain legal rights.You may have other rights under the laws of your country.

                You may also have rights with respect to the party from whom you acquired the software.

    This agreement does not change your rights under the laws of your country if the laws of your country do not permit it to do so.

9. Disclaimer of Warranty.The software is licensed "as-is."  You bear the risk of using it.

                IE and EDGE Internals gives no express warranties, guarantees or conditions.You may have additional consumer rights under your local laws which this agreement cannot change.

                To the extent permitted under your local laws, IE and EDGE Internals excludes the implied warranties of merchantability, fitness for a particular purpose and non - infringement.

10. Limitation on and Exclusion of Remedies and Damages.You can recover from IE and EDGE Internals and its suppliers only direct damages up to U.S.$5.00.

    You cannot recover any other damages, including consequential, lost profits, special, indirect or incidental damages.

                This limitation applies to

                · anything related to the software, services, content(including code) on third party Internet sites, or third party programs; and

                · claims for breach of contract, breach of warranty, guarantee or condition, strict liability, negligence, or other tort to the extent permitted by applicable law.

                It also applies even if IE and EDGE Internals knew or should have known about the possibility of the damages.

    The above limitation or exclusion may not apply to you because your country may not allow the exclusion or limitation of incidental, consequential or other damages.



Please note : As this software is distributed in Quebec, Canada, some of the clauses in this agreement are provided below in French.

Remarque : Ce logiciel étant distribué au Québec, Canada, certaines des clauses dans ce contrat sont fournies ci - dessous en français.

EXONÉRATION DE GARANTIE.Le logiciel visé par une licence est offert « tel quel ».Toute utilisation de ce logiciel est à votre seule risque et péril.

IE and EDGE Internals n'accorde aucune autre garantie expresse. Vous pouvez bénéficier de droits additionnels en vertu du droit local sur la protection dues consommateurs, que ce contrat ne peut modifier.

La ou elles sont permises par le droit locale, les garanties implicites de qualité marchande, d'adéquation à un usage particulier et d'absence de contrefaçon sont exclues.

LIMITATION DES DOMMAGES - INTÉRÊTS ET EXCLUSION DE RESPONSABILITÉ POUR LES DOMMAGES.Vous pouvez obtenir de IE and EDGE Internals et de ses fournisseurs une indemnisation en cas de dommages directs uniquement à hauteur de 5, 00 $ US.

Vous ne pouvez prétendre à aucune indemnisation pour les autres dommages, y compris les dommages spéciaux, indirects ou accessoires et pertes de bénéfices.

Cette limitation concerne :

                · tout ce qui est relié au logiciel, aux services ou au contenu(y compris le code) figurant sur des sites Internet tiers ou dans des programmes tiers; et

                · les réclamations au titre de violation de contrat ou de garantie, ou au titre de responsabilité stricte, de négligence ou d'une autre faute dans la limite autorisée par la loi en vigueur.

Elle s'applique également, même si IE and EDGE Internals connaissait ou devrait connaître l'éventualité d'un tel dommage.

Si votre pays n'autorise pas l'exclusion ou la limitation de responsabilité pour les dommages indirects, accessoires ou de quelque nature que ce soit, il se peut que la limitation ou l'exclusion ci - dessus ne s'appliquera pas à votre égard.

EFFET JURIDIQUE.Le présent contrat décrit certains droits juridiques.Vous pourriez avoir d'autres droits prévus par les lois de votre pays.

Le présent contrat ne modifie pas les droits que vous confèrent les lois de votre pays si celles-ci ne le permettent pas.



Kind regards.

Pierre-Louis


________________________________

**Comment by pierrecoll** [comment]
You should find the latest signed version on http://ieee.azurewebsites.net/pierrelc.

**Comment by nixtar** [comment]
Hi @pierrecoll,

Getting an error when trying to access http://ieee.azurewebsites.net/pierrelc

Error 403 - This web app is stopped.

The URI linked from the following MS doc also gives the same 403. https://learn.microsoft.com/en-us/troubleshoot/developer/browsers/connectivity-navigation/optimize-pac-performance#testing-with-autoproxexe

Happy to open a new issue or log a case with MS elsewhere if you would prefer.
